services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ../public:/var/www/html
      - ../src:/var/www/src
    depends_on:
      - db
    networks:
      - app-network
    command: >
      bash -c "
        chown -R www-data:www-data /var/www/html &&
        chmod -R 777 /var/www/html &&
        apache2-foreground
      "

  db:
    image: mariadb:${DB_VERSION}
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Rome
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
